spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

decorator:
  datasource:
    p6spy:
      enable-logging: true